# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_description', models.TextField()),
                ('content', models.ImageField(blank=True, upload_to=None)),
                ('post_type', models.CharField(max_length=50)),
                ('likes', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('dislikes', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('A', 'Active'), ('R', 'Reported'), ('B', 'Blocked')], max_length=50)),
                ('shared_with', models.CharField(choices=[('F', 'Friends'), ('FOF', 'Friends of Friends'), ('P', 'Public')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
