# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_who_disliked',
            field=models.ManyToManyField(blank=True, related_name='user_who_disliked', to='user.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_who_liked',
            field=models.ManyToManyField(blank=True, related_name='user_who_liked', to='user.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_who_posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_posted', to='user.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_commented', to='user.user'),
        ),
    ]
