# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('n_type', models.CharField(choices=[('B', 'B'), ('U', 'U')], max_length=50)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('B', 'B'), ('U', 'U')], max_length=50)),
            ],
        ),
    ]
