# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rules', models.TextField()),
                ('registration_time', models.DateField(auto_now_add=True)),
                ('total_number_of_subscribers', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
