# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('community', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admin_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='community',
            name='community_posts',
            field=models.ManyToManyField(related_name='community_post', to='post.Post'),
        ),
        migrations.AddField(
            model_name='community',
            name='pinned_posts',
            field=models.ManyToManyField(related_name='pinned_post', to='post.Post'),
        ),
    ]
