# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisement_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.ImageField(blank=True, upload_to='advertisement/advertisement')),
                ('text_description', models.TextField()),
                ('audience_details', models.TextField()),
                ('advertisement_link', models.URLField()),
                ('user_preference', models.CharField(max_length=50)),
                ('money_credit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('view_need_to_shown', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'A'), ('D', 'D'), ('E', 'E'), ('B', 'B')], max_length=50)),
            ],
        ),
    ]
