# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='advertise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.advertiser'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user_who_watched',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
