# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('B', 'B'), ('MR', 'MR'), ('ME', 'ME'), ('EE', 'EE')], max_length=50)),
            ],
        ),
    ]
