# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='going_user',
            field=models.ManyToManyField(blank=True, related_name='going_user', to='user.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='intrested_user',
            field=models.ManyToManyField(blank=True, related_name='interested_user', to='user.User'),
        ),
    ]
