# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('newsfeed_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
