# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='fr_send_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_send_by', to='user.user'),
        ),
        migrations.AddField(
            model_name='friend',
            name='fr_send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_send_to', to='user.user'),
        ),
    ]
