# Generated by Django 3.1.1 on 2020-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
